unified_mode     'true'
name             'rb-firewall'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures Firewall'
version          '0.10.1'
